### ISSUE TITLE
Update contribute.md

### ISSUE THREAD

**Issue by JackieBinya** [creativecommons/wp-theme-base#14]
## Problem

* In [contribute.md](https://github.com/creativecommons/wp-theme-base/blob/master/CONTRIBUTE.md#recommended-setup-for-wordpress-coding-standards)  under the heading **Recommended Setup for WordPress Coding Standards** in item 3 titled **Confirm Installation** the suggested `PATH` will not work with linux Ubuntu 20.04 distribution. Instead this one below works: 
``
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
``

    * I followed the outlined contributing instructions but as I was using `composer` to install the `php code sniffer` instead of creating a `.composer` folder for the configs the system created a `.config/composer` directory. The differences in the installation procedure might be either due to differences in OS or its coming up because of updates. 

*  Prospective contributors are not advised to run `composer install` after project setup so as to install package dependencies

* In addition to that contributors should be informed that the dependency `Quelat` will not load automatically despite being a `mu-plugin` and advised how to proceed. I personally used the `composer auto-loader`.

## Description

I recommend we update `contribute.md` and add that detail so as to ensure faster on-boarding of linux Ubuntu contributors.

## Alternatives

- N/A

## Implementation

 Edit the docs where there is a problem area, by just adding a statement detailing what would work for Ubuntu users and also by enriching the docs' content so as to make it more intuitive.
-  [x]  I would be interested in implementing this feature.

**Comment by hugosolar** [comment]
Hey @JackieBinya thank you so much for pointing this out
You're right about the incomplete documentation (still a work in progress)
I'll appreciate your contributions regarding this
Thanks!
