### ISSUE TITLE
Theme gives error when uploaded to wordpress

### ISSUE THREAD

**Issue by av-00** [creativecommons/wp-theme-base#3]
## Describe the bug

When tried to upload this theme to wordpress, it gives an error in `functions.php`. Tried in **localhost**.
## To Reproduce

1. Upload theme in wordpress
2. Activate theme
## Screenshots

![IMG-20200404-WA0010](https://user-images.githubusercontent.com/43967251/78510361-41338180-77b2-11ea-8fea-d858fa773315.jpg)

## Desktop (please complete the following information)
 - OS: Windows and Ubuntu

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context

The files that have been linked have different names, they need to be updated in `functions.php`

**Comment by hugosolar** [comment]
This theme is under development. it's not ready to use. However the error has been fixed
